#!/usr/local/bin/python2.7

import os
i = 0
for root, dirs, files in os.walk("/usr/home/laurent/backup"):
    for file in files:
        if file.endswith(".jpg"):
             print(os.path.join(root, file))
             i += 1

print(i)
